version: "3.4"

services:
  conexao-tech:
    restart: always
    build:
      context: ./
    container_name: conexao-tech
    entrypoint: npm run test:watch
    networks:
      - pontal_network
    volumes:
      - .:/usr/src/app
    tty: true
    ports:
      - "7000:4000"
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          memory: 128M
          cpus: '0.3'
        limits:
          memory: 512M
          cpus: '1'

  rabbitmq:
      image: rabbitmq:3-management
      hostname: rabbitmq
      container_name: rabbitmq
      ports:
        - "5672:5672"  
        - "15672:15672" 
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq
      networks:
      - pontal_network

volumes:
  rabbitmq_data:

networks:
  pontal_network:
    external: true